USE codeup_test_db;
TRUNCATE albums;
    INSERT INTO albums(artist, name, release_date, sales, genre)
    VALUES ('Led Zeppelin', 'Led Zeppelin IV', 1971, 30.4, 'Hard Rock'),
          ('Michael Jackson', 'Bad', 1987, 21.2, 'Pop'),
          ('Alanis Morissette', 'Jagged Little Pill', 1995, 25.4, 'Alternative Rock'),
          ('Bill Medley', 'Dirty Dancing', 1987, 24.1, 'Pop'),
          ('Celine Dion', 'Falling Into You', 1996, 21.1, 'Pop'),
          ('The Beatles', 'Abbey Road', 1967, 16.9, 'Rock'),
          ('Michael Jackson', 'Dangerous', 1991, 17.0, 'New Jack Swing'),
          ('The Beatles', 'Sgt. Peppers Lonely Hearts Club Band', 1967, 17.0, 'Rock'),
          ('Pink Floyd', 'The Wall', 1979, 19.8, 'Progressive Rock'),
          ('Madonna', 'The Immaculate Collection', 1990, 19.8, 'Pop'),
          ('Santana', 'Supernatural', 1990, 20.8, 'Latin Rock'),
          ('Dire Straits', 'Brothers In Arms', 1985, 21.1, 'Roots Rock'),
          ('ABBA', 'Gold: Greatest Hits', 1992, 21.6, 'Pop'),
          ('Bruce Springsteen', 'Born In The U.S.A.', 1984, 22.0, 'Heartland Rock'),
          ('Guns N Roses', 'Appetite for Destruction', 1987, 22.8, 'Hard Rock'),
          ('Bob Marley & The Wailers', 'Legend: The Best of Bob Marley & The Wailers', 1984, 22.9, 'Reggae'),
          ('Celine Dion', 'Lets Talk About Love', 1997, 20.5, 'Pop'),
          ('Metallica', 'Metallica', 1997, 22.7, 'Heavy Metal'),
          ('The Beatles', '1', 2000, 23.2, 'Rock'),
          ('Adele', '21', 2011, 27.1, 'Pop'),
          ('AC/DC',' Back in Black', 1980, 30.1,'Hard rock'),
          ('Michael Jackson', 'Thriller', 1982, 51.2, 'Pop'),
          ('Whitney Houston', 'The Bodyguard', 1992, 28.7,'R&B'),
          ('Pink Floyd', 'The Dark Side of the Moon', 1973, 24.8,'Progressive rock'),
          ('Eagles', 'Their Greatest Hits (1971–1975)', 1976, 41.2,'Country rock'),
          ('Meat Loaf', 'Bat Out of Hell', 1977, 22, 'Hard rock'),
          ('Eagles', 'Hotel California', 1976, 31.8, 'Soft rock'),
          ('Shania Twain', 'Come On Over', 1997, 30.4,'Country, pop'),
          ('Fleetwood Mac', 'Rumours', 1977, 29.3, 'Soft rock'),
          ('Bee Gees', 'Saturday Night Fever', 1977, 22.1, 'Disco');
